version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.27.1
    container_name: prometheus
    network_mode: 'host'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: 'host'