spring:
  #PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: zxc
    driver-class-name: org.postgresql.Driver

  #JPA
  jpa:
    hibernate:
      ddl-auto: update

  #MongoDB
  data:
    mongodb:
      database: hospital
      host: localhost
      port: 27017

  #Kafka
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: appointments
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    topic1:
      name: appointment-request
    topic2:
      name: appointment-accept
    topic3:
      name: appointment-finish
#JWT Token
security:
  jwt:
    token:
      secret-key: mirasmadiyevandazharadilkhan
      expiration: 3600000

#Server
server:
  port: 8080

#Swagger
springdoc:
  swagger-ui:
    configUrl: /api/v1/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /api/v1/api-docs
  api-docs:
    path: /api/v1/api-docs
    version: openapi_3_0

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: 'health, prometheus, info'
  endpoint:
    metrics:
      enabled: true

#Application
application:
  title: Hospital Management System Application
  version: V1.0



